version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: latest

- name: webapp2
  version: latest

handlers:
- url: /save
  script: xmlstore.app

- url: /curr
  script: datafetch.app
  
- url: /fetch
  script: datafetch.app